base_path: /gwteray/users/govoni/OneLeptonSkims
bkg_path: Apr2017_summer16_SingleLepton_hercules
bkg_steps: 
  - lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC__l1tightChain__bvetoTight__LepTrgFix__dorochester__formulasMC__gr4JetsSkim