base_path: /gwteray/users/govoni/OneLeptonSkims
bkg_path: /Apr2017_summer16_SingleLepton_hercules
bkg_steps: 
  - __gr4JetsSkim: /lepSel__MCWeights__bSFLpTEffMulti__cleanTauMC__l1tightChain__bvetoTight__LepTrgFix__dorochester__formulasMC__gr4JetsSkim/

# all the specified steps are automatically added to the column list
table_columns:
  - used
  - desired
  - priority
  # - das_name

# all the cuts are in AND relation
cut:
  - desired: True
  # - priority: high